version: "3.8"

services:
  web:
    build: .
    volumes:
      - ./website:/var/www/html
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: visits
